version: "3.7"

networks:
  mysql-network:
    driver: bridge

services:
  mysql:
    image: mysql:8.0
    ports: 
        - "3306:3306"
    command: --default-authentication-plugin=caching_sha2_password
    environment:
        MYSQL_DATABASE: gitea
        MYSQL_USER: gitea
        MYSQL_PASSWORD: 0918342820
        MYSQL_ROOT_PASSWORD: 09!8342820
    volumes:
        - mysql-persistent:/var/lib/mysql
    networks:
      - mysql-network          

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
        - mysql:db
    ports:
        - 9090:80
    environment:
        MYSQL_USER: gitea
        MYSQL_PASSWORD: 0918342820
        MYSQL_ROOT_PASSWORD: 09!8342820
    networks:
      - mysql-network

  gitea:
    image: gitea/gitea
    restart: always
    environment:
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=0918342820
    volumes:
      - gitea-persistent:/var/lib/gitea
#      - ./config:/etc/gitea
#      - /etc/timezone:/etc/timezone:ro
#      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:2222"
    links:
      - mysql:db
    networks:
      - mysql-network          

volumes:
  mysql-persistent:
  gitea-persistent:
